version: "3"
name: "restreamer"

## XIU local test (no swarm)

# ------------------------------------------------------------------------------

# App containers

# Restremer 'pod'
services:

  # 1. Base streamer
  streamer:
    build:
      context: "git@github.com:user/repo.git#ci"
      platforms:
        - linux/x86_64
      target: "runner"
      args:
        TZ: "Africa/Nairobi"
    # build: "https://github.com/puntopunto/xiu-rndfrk.git"
    image: "normkd/1688557675-test01:1.0.0"
    container_name: "${COMPOSE_PROJECT_NAME}.root"
    volumes:
      # App config volume
      - "streamer_config:/app/config"
    environment:
      TZ: "Europe/Moscow"
    healthcheck:
      test: ["CMD", "ping", "-c", "4", "ya.ru"]
      interval: "5m"
      timeout: "30s"
      retries: 3
      start_period: "5s"
    hostname: "streamer-00"
    networks:
      - intra
    # command: ["-c", "config/config_rtmp.toml"]

# ------------------------------------------------------------------------------
# Pod settings

# Networking
networks:
  intra:
    external: false
    attachable: false
    enable_ipv6: false
    name: "restreamer_pod"
    driver: "ipvlan"
    driver_opts:
      ipvlan_mode: "l2"
      ipvlan_flag: "bridge"
      subnet: "172.100.100.0/24"
      ip_range: "172.100.100.0/28"
      gateway: "172.100.100.10"
    ipam:
      config:
        - subnet: "172.100.100.0/24"
        - ip_range: "172.100.100.0/28"
        - gateway: "172.100.100.10"

volumes:
  streamer_config:
    name: "streamer_config"
    labels:
      type: "ru.mgz.hq.lab0.cr.volume"
      access: "ru.mgz.hq.lab0.cr.volume.access:shared"
