[package]
name = "xrtsp"
version = "0.3.0"
description = "A rtsp library."
edition = "2021"
authors = ["HarlanC <wawacry@qq.com>"]
license = "MIT"
repository = "https://github.com/harlanc/xiu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
byteorder = "1.4.2"
tokio = "1.4.0"
bytes = "1.0.0"
log = "0.4"
failure = "0.1.8"
http = "0.2.9"
indexmap = "1.9.3"
lazy_static = "1.4.0"
chrono = "0.4"
async-trait = "0.1.70"
base64 = "0.21.2"
hex = "0.4.3"
serde_json = { version = "1", default-features = false, features = [
    "alloc",
    "raw_value",
    "std",
] }

bytesio = "0.3.4"
streamhub = "0.2.4"
commonlib = "0.1.2"
