version: "3.8"
# name: "xiu-streamer-test"

# XIU test pod
services:
  stream1:
    image: "normkd/1688557675-11da8b5844776744b42ffae53506bca8:1.0.0"
    build:
      context: "."
      target: "runner"
    # container_name: "${COMPOSE_PROJECT_NAME}.node"
    hostname: "streamer"
    networks:
    - "local"
    ports:
    - "80:80"
    - "80:80/udp"
    - "443:443"
    - "1935:1935"
    - "1935:1935/udp"
    - "1936:1936"
    - "1936:1936/udp"
    - "8000:8000"
    - "8000:8000/udp"
    - "8080:8080"
    - "8080:8080/udp"
    - "8081:8081"
    - "8001:8001/udp"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    deploy:
      replicas: 3
      endpoint_mode: "dnsrr"
      labels:
        nodes.replicated: "Replicated solve."

configs:
  xiu_config:
    file: "config/config_rtmp.toml"
    name: "rtmp_conf"

networks:
  local:
    name: "lan"
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.16.100.0/24
